this.project:
  topic: "topic-from-config"
  topic2: "topic-from-config-2"
server:
  port: 9191

spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092